### ISSUE TITLE
IBM Cloud VPC block storage manager - Status is not being displayed correctly

### ISSUE THREAD

**Issue by chadh1313** [ManageIQ/manageiq-providers-ibm_cloud#101]
As many/most of these are attached to an instance, I would expect the status to reflect `in-use`, etc.

![image](https://user-images.githubusercontent.com/3876941/97316608-4fc1b300-1840-11eb-9587-9ffd04624370.png)

**Comment by bsogithub** [comment]
As far as I can tell, all volumes on IBM cloud has available status whether they are attached or not:
![image](https://user-images.githubusercontent.com/29459925/97364050-d47cf300-1879-11eb-8b89-8c32a0e2940a.png)

However, they do have indication of whether the volume is attached/in use or not:
![image](https://user-images.githubusercontent.com/29459925/97364243-1f970600-187a-11eb-8125-8cbb17d60ae0.png)

![image](https://user-images.githubusercontent.com/29459925/97364320-42c1b580-187a-11eb-81c9-f26a0ca69166.png)

**Comment by jaredm-ibm** [comment]
I'm playing with a small check to see if the length of volume_attachments is zero.

<img width="977" alt="vol_attached" src="https://user-images.githubusercontent.com/60901094/99813973-5a592a80-2b16-11eb-939c-f09edd12a339.png">
