### ISSUE TITLE
IBM Cloud VPC - Single-valued tags on VMs are not captured in tag/label discovery

### ISSUE THREAD

**Issue by chadh1313** [ManageIQ/manageiq-providers-ibm_cloud#102]
Tags in IBM Cloud can be name-value pairs or single-valued.

![image](https://user-images.githubusercontent.com/3876941/97317354-18073b00-1841-11eb-9d7c-cb169dccd92b.png)

Not sure if this is an issue with the SDK or the provider, but only the name-value pairs are currently being discovered.

![image](https://user-images.githubusercontent.com/3876941/97317423-2c4b3800-1841-11eb-9dd4-a86173c8b8be.png)

**Comment by jaredm-ibm** [comment]
I think Omar fixed this in https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/104
