### ISSUE TITLE
IBM Cloud VPC - tags from tag mapping cannot be viewed in instance details

### ISSUE THREAD

**Issue by chadh1313** [ManageIQ/manageiq-providers-ibm_cloud#103]
Having set up tag mapping for IBM Cloud Instances, I see a new tag generated as expected in an Instance overview page.

![image](https://user-images.githubusercontent.com/3876941/97317675-6b798900-1841-11eb-8a03-13f813b9b80b.png)

However, going to Policy->Edit Tags does not show me this tag.  Note this is running from dev environment, where I see several UI error appearing, which could affect this behavior.  Need to ensure this is working properly in an actual build.

![image](https://user-images.githubusercontent.com/3876941/97317875-aa0f4380-1841-11eb-9b91-168030a470b3.png)

**Comment by gtanzillo** [comment]
@chadh1313 If you change the tag mapping to be "All Entities" and select "Environment" as the category it will display.

**Comment by chadh1313** [comment]
@gtanzillo Confirmed what suggested works, and in fact the format is different (better) than the one mapped specifically to IBM VPC VMs.

![image](https://user-images.githubusercontent.com/3876941/98300481-527e7f80-1f87-11eb-8281-cf28068a7248.png)

I wouldn't have expected these to look different.  Is there still a defect somewhere either in core or the VPC provider that we need to address?  If both are valid tags, I would expect both of them to show in the `Edit Tags` view

**Comment by gtanzillo** [comment]
@chadh1313 The "All Entities" was the result of the work that we did to enable mapping external labels to "Managed tags", those are the tags that you can create/edit in the regional settings under "My Company Categories" and "My Company Tags".  This is the issue - https://github.com/ManageIQ/manageiq/issues/20408

Mapping by other entities will create categories that are prefixed by `<provider type>:<resource type>` which prevents them from being visible in the places where managed tags are.

**Comment by chadh1313** [comment]
Closing since working as designed
