### ISSUE TITLE
Edit cloud volume got a loading icon on Save

### ISSUE THREAD

**Issue by bsogithub** [ManageIQ/manageiq-providers-ibm_cloud#109]
Steps:
1) Go to Storage > Block Storage > volumes
2) Select a ibm cloud volume and selected Configuration > Edit selected Cloud Volume
3) Change the volume name and click the Save button.
You will get something similar to the following:

![image](https://user-images.githubusercontent.com/29459925/98032030-61c3c880-1de1-11eb-9627-517f1e1fb05e.png)

You cannot Save/Reset/Cancel. You can only refresh or go to another page and abandon change.

**Comment by jaywcarman** [comment]
I ran into something similar with the subnet create form in PowerVS:
https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/93#issuecomment-713003336
