### ISSUE TITLE
IBM Cloud VPC Provider for Lasker

### ISSUE THREAD

**Issue by blancett** [ManageIQ/manageiq-providers-ibm_cloud#125]
Infrastructure

- [x] Create Helper methods to make accessing Open API easier - **in progress**  (https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/137)
- [x]  Rebase on OpenAPI-based ruby gem for IBM Cloud SDK.   - **in progress** (https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/137)

**Comment by blancett** [comment]
A subset of #92

**Comment by blancett** [comment]
@jaredm-ibm is working on - Create Helper methods to make accessing Open API easier and Rebase on OpenAPI-based ruby gem for IBM Cloud SDK.  Should have done this week.

**Comment by chessbyte** [comment]
@blancett @chadh1313 whatever items will not make it into Lasker, please create a new issue named "IBM Cloud VPC Provider for Morphy" and move the items there.

**Comment by agrare** [comment]
I split out uncompleted tasks into https://github.com/ManageIQ/manageiq-providers-ibm_cloud/issues/146
