### ISSUE TITLE
[Najdorf] IBM Cloud PowerVS Provider Enhancements

### ISSUE THREAD

**Issue by jaywcarman** [ManageIQ/manageiq-providers-ibm_cloud#147]
Power Virtual Servers and PowerVC provider features targeted for Morphy Release:

- [x] PowerVC -> PowerVS cross cloud-provider image import #180
- [x] New IBM Cloud Object Storage provider #159 
- [x] Add event handler (https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/279)
- [x] Collect snapshots (https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/313)
- [x] Snapshots
  - [x] Create snapshots https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/325
  - [x] Delete snapshots https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/327
  - [x] Revert to snapshot https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/331
  - [x] Calculate snapshot size https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/332

**Comment by agrare** [comment]
Split out issues which are being backported to Morphy in https://github.com/ManageIQ/manageiq-providers-ibm_cloud/issues/269

**Comment by jaywcarman** [comment]
Couple of updates to comment on:
- Remove `Enable chargeback rate assignments based on Power related attributes (e.g. entitled processors).` We'll defer this to a future release. There are still some reporting "enhancements" I'd like to make for existing reports (consistent names, tweaks, etc.).
- Add `VM affinity for multi-VM create`. PowerVS allow us to specify affinity/anti-affinity when creating VMs. We'd like to add this to the existing VM provision workflow.
