### ISSUE TITLE
[RFE] Support IBM Cloud Kubernetes Service (IKS)

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-providers-ibm_cloud#149]
Add support for [IBM Cloud Kubernetes Service](https://www.ibm.com/cloud/kubernetes-service) to ManageIQ

- [x] Provider https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/272
- [x] Icon https://github.com/ManageIQ/manageiq-decorators/pull/54
- [x] IAM headers https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby/pull/66
- [x] Capabilities Matrix

**Comment by agrare** [comment]
Docs are in conflict but the main code has been backported, moving to morphy
