### ISSUE TITLE
[LASKER] Cannot edit Cloud provider - PowerVS Provider Name

### ISSUE THREAD

**Issue by Kuldip-Nanda** [ManageIQ/manageiq-providers-ibm_cloud#162]
From `[Compute]/[Cloud Provider]`
1. From `[Configuration]/[Add a new Cloud Provider]` add a new provider with
     Type: IBM Power System Virtual server
      Name: Frankfurt2
      Zone: default
      Endpoint: <Your API KEY>
      Power VS GUID: fca73cd3-8627-45fc-b09b-50253249cf3f
2. Now go to the `[Provider List]` and select the Frankfurt2 provider.
3. Select `[Configuration]/[Edit Selected Provider]` menu.
4. Change the name of the Provider in `Edit Cloud Provider Frankfurt2` to Frankfurt02
5. User gets `500 Internal Server Error`
6. Click Close, go back. The name is changed. 

However one cannot edit the provider again as you will always get the same 500 error as shown below

**Comment by Kuldip-Nanda** [comment]
![Screen Shot 2021-03-22 at 9 04 03 AM](https://user-images.githubusercontent.com/5939617/111995331-2fe0a380-8aef-11eb-9f07-99c6dc8c2b81.png)
[](url)

**Comment by Kuldip-Nanda** [comment]
@miq-bot add_label bug

**Comment by Kuldip-Nanda** [comment]
@assign @jaywcarman

**Comment by Fryguy** [comment]
Seems related to #164

**Comment by jaywcarman** [comment]
Re-tested this in the latest _master_ (de48f6c) and now see a different fail mode. @vinisawa opened #371 with an updated description - closing this issue.
