### ISSUE TITLE
[LASKER] Adding same PowerVS provider multiple times with different names

### ISSUE THREAD

**Issue by Kuldip-Nanda** [ManageIQ/manageiq-providers-ibm_cloud#163]
**Same Provider GUID with different names**

From Cloud Provider
1. From [Configuration]/[Add a new Cloud Provider] add a new provider with
   Type: IBM Power System Virtual server
    Name: Frankfurt2
   Zone: default
   Endpoint: Power VS GUID: fca73cd3-8627-45fc-b09b-50253249cf3f
2. For a Cloud Provider/
    From [Configuration]/[Add a new Cloud Provider] add a new provider with
    Type: IBM Power System Virtual server
    Name: Frankfurt-02
    Zone: default
    Endpoint: Power VS GUID: fca73cd3-8627-45fc-b09b-50253249cf3f

**Comment by Kuldip-Nanda** [comment]
@miq-bot add_label bug

**Comment by Fryguy** [comment]
This can probably be handled with a model validation which will raise an error to the user.  cc @jaywcarman
