### ISSUE TITLE
[LASKER] Changing the name of the PowerVSProvider in edit causes errors

### ISSUE THREAD

**Issue by Kuldip-Nanda** [ManageIQ/manageiq-providers-ibm_cloud#164]
If name of the provider for PowerVS is changed, subsequent edits will give `500 Internal Server Error` with error message `Missing credentials`,
![Screen Shot 2021-03-22 at 9 04 03 AM](https://user-images.githubusercontent.com/5939617/112017143-ba330280-8b03-11eb-9147-8b6d52570cd0.png)

**Comment by Kuldip-Nanda** [comment]
@miq-bot add_label bug

**Comment by agrare** [comment]
I'm guessing on edit the pcloud_guid isn't being passed back in somehow: https://github.com/ManageIQ/manageiq-providers-ibm_cloud/blob/master/app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb#L156-L158

On edit anything that isn't passed in should be looked up from the manager by ID: https://github.com/ManageIQ/manageiq-providers-ibm_cloud/blob/master/app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb#L150

**Comment by Fryguy** [comment]
In chat we discussed that once the PowerVS GUID is set, it probably should be allowed to be changed.  I'm not sure how, but we'll have to find a DDF way to do that, I presume.

cc @jaywcarman

**Comment by Fryguy** [comment]
+1 for what @agrare said...not all values will come from the form, particularly on edit.  Credentials, specifically, will never come back, because we never send them from the server to the user (and so they have nothing to send back unless they change them)

**Comment by jaywcarman** [comment]
Re-tested this in the latest _master_ (de48f6c) and now see a different fail mode. @vinisawa opened #371 with an updated description - closing this issue.

@Kuldip-Nanda - can you give me a quick sanity check? Is there a difference between #162 and #164 ? They look exactly the same to me.
