### ISSUE TITLE
[LASKER] All PowerVS provides have 0 marked as region.

### ISSUE THREAD

**Issue by Kuldip-Nanda** [ManageIQ/manageiq-providers-ibm_cloud#165]
`Compute/Cloud/Providers/` screen shows all the PowerVS providers having Region 0. Please see below
![Screen Shot 2021-03-22 at 12 00 05 PM](https://user-images.githubusercontent.com/5939617/112020246-902f0f80-8b06-11eb-880a-7ad7e5663fbe.png)

While we have in Gen2 different regions.
![Screen Shot 2021-03-22 at 10 37 35 AM](https://user-images.githubusercontent.com/5939617/112020399-adfc7480-8b06-11eb-80d4-0fbcf332ee55.png)

**Comment by Kuldip-Nanda** [comment]
@miq-bot add_lable bug

**Comment by Fryguy** [comment]
That Region is the ManageIQ region, which in your case is 0.  It's admittedly weird, but not wrong.  You might want to open an issue in the UI repo to have that column renamed.

**Comment by jaywcarman** [comment]
More information to include if we open an issue against UI:
The default 'provider_region' value is actually `nil`, which the UI displays as `Region 0` (maybe there's a default region?).

**Comment by agrare** [comment]
I think the confusing is: Provider Region != Region

Each MIQ Region is essentially a different database instance, and I imagine that column would be helpful for the "global region" where you would see providers listed from multiple MIQ Regions

It would be nice to also see the provider region in that list, but I don't know that `Region` is the wrong name for that column.
