### ISSUE TITLE
[LASKER] Adding a same key with different name.

### ISSUE THREAD

**Issue by Kuldip-Nanda** [ManageIQ/manageiq-providers-ibm_cloud#171]
The key is added and log also shows an unexpected error:
  `undefined method fingerprint for #<IbmCloudPower:SSHKey:0x00005596411fe39e0>`.
 Not clear where this is coming from.

**Comment by Kuldip-Nanda** [comment]
@miq_bot add_label bug

**Comment by jaywcarman** [comment]
I was able to add a key in _master_ (manageiq-providers-ibm_cloud eefc54c + manageiq 946e01a) that had a new & unique name, but used a public ssh key that is already used in an existing key. Can you provider some more details on the error you saw (build level, logs, backtrace for the exception, etc.)?

Also, can you clarify what you mean by "a key with wrong name"?

**Comment by jaywcarman** [comment]
I think this is the `fingerprint` method call mentioned in your exception:
https://github.com/ManageIQ/manageiq/blob/master/app/models/manageiq/providers/cloud_manager/auth_key_pair.rb#L46
