### ISSUE TITLE
[LASKER] Clicking on the Setting/Tasks

### ISSUE THREAD

**Issue by Kuldip-Nanda** [ManageIQ/manageiq-providers-ibm_cloud#172]
If you mouse click on any task in Setting/Tasks one gets 
```
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
```
![Screen Shot 2021-03-24 at 5 57 48 PM](https://user-images.githubusercontent.com/5939617/112389280-e2209280-8cca-11eb-9262-6750392014c5.png)

**Comment by Kuldip-Nanda** [comment]
@miq-bot add_label bug

**Comment by Fryguy** [comment]
Is this an IBM Cloud specific issue?  If it's more general, please open the issues in the core https://github.com/ManageIQ/manageiq repo or if you think they are UI specific in https://github.com/ManageIQ/manageiq-ui-classic

**Comment by Fryguy** [comment]
Going to close for now as multiple people have confirmed this works.  If you still have this issue, and it's a UI issue, please open in https://github.com/ManageIQ/manageiq-ui-classic

**Comment by Kuldip-Nanda** [comment]
I will move this issue to  https://github.com/ManageIQ/manageiq-ui-classic as this is reproducible in 2.3 candidate builds.
