### ISSUE TITLE
[LASKER] Multiple issues found while trying to Add New Cloud Volume

### ISSUE THREAD

**Issue by Kuldip-Nanda** [ManageIQ/manageiq-providers-ibm_cloud#174]
This issue may well be UI but right now parking it here.

1. Go to `Storage/Volume/Configuration/Add a new Volume`
2. Choose TestCloud Dallas Block Manager.
3. Volume Name as AlphatSorage 
4. On Size in bytes double click down arrow

These are what is seen 
1. Double click gives negative Size in bytes
2. If the negative size comes, user cannot do anything except make it 0 and then entering a return, `Add of Cloud Volume "KuldipTest3" has been successfully queued.` message comes. (Seems Add key at the bottom becomes enabled and focus shifts to that key)
3. If you enter  `up arrow key` on `Size (in bytes)`, `Required Message` comes with Add button at the bottom  disabled. 
4. Add some numbers and only then the Required field disappears. 
    (If Required key can be displayed at the bottom, then one can also display size in Gig. Just some suggestion)

5. Choose Cloud Volume Type to Standard
6. Sharable to No and Affinity Policy to Off.
Now add the Volume
We see Cloud Volumes with message `Add of Cloud Volume "KuldipTest10" has been successfully queued.`

Searching the Volume after some time gives no result.
I also did not find the Volume created in ibm cloud.

**Comment by Kuldip-Nanda** [comment]
@miq-bot add_label bug

**Comment by jaywcarman** [comment]
Thanks @Kuldip-Nanda ! I'd like to try and break this up into single issues we can tackle with PRs. I started working my way through your notes got slowed down by #175. I'll continue tomorrow morning.
