### ISSUE TITLE
Unable to create an allocation based Utilization Report.

### ISSUE THREAD

**Issue by Kuldip-Nanda** [ManageIQ/manageiq-providers-ibm_cloud#214]
I think we are following all the steps listed for creating a C&U report but we are unable to get the allocation based utilization data.
1. I have a PowerVS Provider Registered with 32 VMs as seen below:
![Screen Shot 2021-05-19 at 3 45 40 PM](https://user-images.githubusercontent.com/5939617/118874829-53d72000-b8b9-11eb-940d-c9726e3374cf.png)
2. I have enabled the C&U as requested:
![Screen Shot 2021-05-19 at 3 49 22 PM](https://user-images.githubusercontent.com/5939617/118875366-fa232580-b8b9-11eb-95b1-43153ae54bca.png)
![Screen Shot 2021-05-19 at 3 48 05 PM](https://user-images.githubusercontent.com/5939617/118875508-22128900-b8ba-11eb-89e6-6bcfe05bb86c.png)

Howevere I am unable to get the Utilization data 
<img width="1434" alt="Screen Shot 2021-05-19 at 2 21 57 PM" src="https://user-images.githubusercontent.com/5939617/118875097-a3b5e700-b8b9-11eb-9706-1d05993a558b.png">

**Comment by Kuldip-Nanda** [comment]
I tried just the allocation based report:
1. Please see the selected columns as below:
![Screen Shot 2021-05-19 at 5 12 38 PM](https://user-images.githubusercontent.com/5939617/118885583-f72e3200-b8c5-11eb-86c3-3876515d50e5.png)
2. In Filter as suggested earlier C&U is disabled:
![Screen Shot 2021-05-19 at 5 13 30 PM](https://user-images.githubusercontent.com/5939617/118885774-2e9cde80-b8c6-11eb-9b32-52454023b5fa.png)

3. However no report is generated for the PowerVS Tenant as seen below:
![Screen Shot 2021-05-19 at 5 19 56 PM](https://user-images.githubusercontent.com/5939617/118886371-d9150180-b8c6-11eb-9d16-a337ec13a8b6.png)

**Comment by agrare** [comment]
@gtanzillo does ^ look like the appropriate steps?  Anything we can check to see where along the process it might have gone wrong that isn't just "no records"

**Comment by gtanzillo** [comment]
@agrare @Kuldip-Nanda 
> @gtanzillo does ^ look like the appropriate steps? Anything we can check to see where along the process it might have gone wrong that isn't just "no records"

Two things to check -
1. Make sure the provider and VMs/instances are actually in the tenant "PowerVS", as it was specified in the filter tab of the report.
2. Make sure there are rates assigned. The report will show "no records ..." if it does not find any rates. The easiest way to do this is to assign rates to "Enterprise". This way the assignment is global and will guarantee every VM/instance will have an assigned rate
