### ISSUE TITLE
Using "IBM" as vendor is too generic with PowerVC provider

### ISSUE THREAD

**Issue by jaywcarman** [ManageIQ/manageiq-providers-ibm_cloud#243]
With the newly created [IBM PowerVC provider](https://github.com/manageiq/manageiq-providers-ibm_power_vc) the "IBM" vendor is overloaded. IBM Cloud and IBM PowerVC use different icons for branding. ManageIQ UI uses `image_name` methods and a hardcode vendor has for VM/templates (https://github.com/ManageIQ/manageiq/blob/master/app/models/vm_or_template.rb#L50).

I propose that we use "IBM Cloud" for the vendor and icons associated with managers in this provider, along with "IBM PowerVC" in the PowerVC provider. If there is a future IBM provider that wants to use the generic IBM 8 bar logo branding, then "IBM" would be appropriate, otherwise something more specific should be used to differentiate.

PRs:
- https://github.com/ManageIQ/manageiq/pull/21333
- https://github.com/ManageIQ/manageiq-decorators/pull/50
- https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/244
- https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/19
- https://github.com/ManageIQ/manageiq-schema/pull/587

**Comment by jaywcarman** [comment]
@nasark this change affects VPC. In #244 I change the VPC image and instance `:vendor` from `ibm` -> `ibm_cloud`. The icons will remain the same as they are now - the IBM Cloud logo.

**Comment by Fryguy** [comment]
cc @agrare

**Comment by kbrock** [comment]
This is nicely done @jaywcarman

**Comment by jaywcarman** [comment]
Thanks for all of the help with this one @agrare and @Fryguy!
