### ISSUE TITLE
IBM Cloud provider for Kasparov

### ISSUE THREAD

**Issue by chadh1313** [ManageIQ/manageiq-providers-ibm_cloud#28]
#### Planned for Kasparov (CP4MCM 2.2)

- [x] Create plugin upstream

- Create/update SDK (https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby)
  - [x] various API calls for VPC infra (details needed)
  - [x] handle pagination of large responses

- [x] Shared auth/connection between VPC and Power virtual servers

- Discover and persist resources/relationships
  - [x] VMs (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/29)
     - [x] hardware (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/29)
     - [x] operating system (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/29)
     - [x] ssh key linking
     - [x] flavor linking https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/41
     - [x] discover/link private IP. ( PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/69)
     - [x] link private IP to floating IP
     - [x] Tags (labels) (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/91)
  - [x] flavors (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/41)
  - [x] Images (public and custom) (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/29)
  - [x] Availability zones  (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/33)
  - [x] Storage volumes discovery (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/54)
    - [x] Storage linkage to VM (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/54)
    - [x] Allocation sizes
    - [x] Volume type, status (in-use)
    
  - [x] VPCs (networks) (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/41)
  - [x] Subnets (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/41)
  - [x] Security groups (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/41)
  - [x] SSH Keys  (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/33)
  - [x] Floating IPs (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/49)

- Verify/enable core functionality in MIQ for IBM Cloud VMs
  - [x] chargeback (allocation)
  - [x] compliance/policy
  - [x] custom VM actions

- Visual Design
  - [x] icons
  
- Test automation

- Other tasks
  - [x] Rename provider to `IBM Cloud VPC`
  - [x] Add other region support with geographical locations (hard-code as needed, expose in settings)
  - [x] Refresh worker (all managers) that runs when provider is created (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/75)
  - [x] Map power states (PR -> https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/42)
  - [x] Pull/map VM/image architecture (64-bit, etc.)
  - [x] Tag mapping for IBM Cloud VPC VMs

**Comment by jaredm-ibm** [comment]
SDK pagination complete https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby/issues/10

**Comment by agrare** [comment]
Hey @chadh1313 now that we're coming up on Kasparov I'm going to split this issue into what we're tracking for the K-release and what is going to be targeted for the next release.

Initially I just took the "Scoped for later development" section and dropped it into https://github.com/ManageIQ/manageiq-providers-ibm_cloud/issues/92 but can you go through this list and pull out anything that isn't going to make Kasparov?
