### ISSUE TITLE
Network spec to fail due to flip-flopping response recorded

### ISSUE THREAD

**Issue by miyamotoh** [ManageIQ/manageiq-providers-ibm_cloud#323]
Bizarre behavior observed during #313 work, which may or may not happen with a different service instance or a different subnet, but here's what I saw.

Steps to reproduce
1. get the code level at or near `4ccd7052f1f5d01935835906b1940cc768001514`
2. comment out `assert_table_counts` and `assert_ems_counts` tests as they can fail very easily based on what's in the target account / service instance at the time.
2. `bin/update && rm spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml && bundle exec rake spec`
3. see the test fail with the below perhaps every other time;
```
Failures:

  1) ManageIQ::Providers::IbmCloud::PowerVirtualServers::CloudManager::Refresher#refresh full refresh
     Failure/Error:
       expect(cloud_subnet).to have_attributes(
         :ems_ref          => "ebc60295-6b51-435a-92db-21a925832cdf",
         :name             => "hiro-test-network",
         :cidr             => "127.0.0.0/24",
         :status           => "active",
         :gateway          => "127.0.0.1",
         :network_protocol => "IPv4",
         :dns_nameservers  => ["127.0.0.1"],
         :extra_attributes => {:ip_version => "4", :network_type => "vlan"},
         :type             => "ManageIQ::Providers::IbmCloud::PowerVirtualServers::NetworkManager::CloudSubnet"
     
       expected #<ManageIQ::Providers::IbmCloud::PowerVirtualServers::NetworkManager::CloudSubnet id: 3000000000066, ...PowerVirtualServers...", network_router_id: nil, network_group_id: nil, parent_cloud_subnet_id: nil> to have attributes {:cidr => "127.0.0.0/24", :dns_nameservers => ["127.0.0.1"], :ems_ref => "ebc60295-6b51-435a-92db-21a925832...>"active", :type => "ManageIQ::Providers::IbmCloud::PowerVirtualServers::NetworkManager::CloudSubnet"} but had attributes {:cidr => "10.0.0.0/24", :dns_nameservers => ["127.0.0.1"], :ems_ref => "ebc60295-6b51-435a-92db-21a925832c...>"active", :type => "ManageIQ::Providers::IbmCloud::PowerVirtualServers::NetworkManager::CloudSubnet"}
       Diff:
       
       @@ -1,8 +1,8 @@
       -:cidr => "127.0.0.0/24",
       +:cidr => "10.0.0.0/24",
        :dns_nameservers => ["127.0.0.1"],
        :ems_ref => "ebc60295-6b51-435a-92db-21a925832cdf",
        :extra_attributes => {:ip_version=>"4", :network_type=>"vlan"},
       -:gateway => "127.0.0.1",
       +:gateway => "10.0.0.1",
        :name => "hiro-test-network",
        :network_protocol => "IPv4",
        :status => "active",
       
     # ./spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb:204:in `assert_specific_cloud_subnet'
     # ./spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb:28:in `block (4 levels) in <main>'
     # ./spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb:17:in `times'
     # ./spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb:17:in `block (3 levels) in <main>'

Finished in 1 minute 54.63 seconds (files took 20.03 seconds to load)
100 examples, 1 failure
```

Note that "127" is what's expected in the spec, while, if you query by hand either via CLI, curl, or even a quick Ruby script calling into the `ibm_cloud_power` gem, "10" is what's returned, consistently.

**Comment by miyamotoh** [comment]
The little Ruby script mentioned above: [https://gist.github.com/miyamotoh/f3de33069e2752cd1cf5ea3a9f879b63](url)

**Comment by Fryguy** [comment]
Very interesting...makes it sound similar to when 2 values being returned in random order (like from the database or from an HTTP request), and it's taking the first one.

**Comment by Fryguy** [comment]
Either that or it's environmental.  I've seen things where when I'm on VPN it records one way and when I'm not on VPN it records a different way.

**Comment by agrare** [comment]
Hey @miyamotoh is this still an issue?

**Comment by miyamotoh** [comment]
The particular subnet was deleted, in the last sprint when Terraform was introduced to provision/destroy the resources for the spec runs. Now with terraform-created subnets, I didn't see any glitches like this when I worked on #345 last week. I don't see a point in keeping this open at this time. Let's close.
