### ISSUE TITLE
Add error message when API Key is incorrect during setup.

### ISSUE THREAD

**Issue by jaredm-ibm** [ManageIQ/manageiq-providers-ibm_cloud#64]
Catch the HTTP error and give a nicer message to the user.

**Comment by gtanzillo** [comment]
@jaredm-ibm Can you provide the current error message here? Thanks

**Comment by jaredm-ibm** [comment]
This is the HTTPStatus error message on status exception. It will only work for the VPC plugin. The Power side is using a different implementation.
```
[6] pry(#<Sdk>)> vpc.instances.params(limit: 'ss').all.first
```
```
IBM::Cloud::SDK::VPC::Exceptions::HttpStatusError: Invalid status 400 for url 
"https://us-east.iaas.cloud.ibm.com/v1/instances?version=2020-08-01&generation=2&limit=ss", 
Bad Request.
{"errors":[{"code":"bad_field",
"message":"The `limit` parameter is invalid, it must be an integer between 1 and 100.","target":{"name":"limit","type":"parameter"}}],
"trace":"e6b897f6-d57f-4b92-8a4e-28157d117acb"}
```

**Comment by jaredm-ibm** [comment]
Oh that error message I posted isn't relevant. It's during setup, before the VPC SDK is being used.

@chadh1313 Can you get the error message we saw yesterday when you put in a wrong API Key?

**Comment by jaredm-ibm** [comment]
Chad got the true error message.

> Validation failed: Invalid status 400 for url "https://iam.cloud.ibm.com/identity/token", Bad Request. {"errorCode":"BXNIM0415E","errorMessage":"Provided API key could not be found","context":{"requestId":"e65140095bdb48c086c71453b895f3b7","requestType":"incoming.Identity_Token","userAgent":"http.rb/4.4.1","url":"https://iam.cloud.ibm.com","instanceId":"iamid-5.9-8603-461329e-8db965548-d92d7","threadId":"1fa867","host":"iamid-5.9-8603-461329e-8db965548-d92d7","startTime":"01.10.2020 20:07:51:368 GMT","endTime":"01.10.2020 20:07:51:423 GMT","elapsedTime":"55","locale":"en_US","clusterName":"iam-id-predal13-5E53"}}

**Comment by jaredm-ibm** [comment]
Will have PR up in a few minutes.
This is when the server returns a standard error hash.
<img width="347" alt="KeyError" src="https://user-images.githubusercontent.com/60901094/99726164-26cdc000-2a84-11eb-9761-a061791d37b1.png">

This is when the server returns an unknown hash.
<img width="304" alt="KeyError2" src="https://user-images.githubusercontent.com/60901094/99726260-449b2500-2a84-11eb-8743-09390f49d6c1.png">

For every other error type, like network failures, I just re-raise the returned error.

**Comment by jaredm-ibm** [comment]
With error with the network down.
<img width="776" alt="NoNetwork" src="https://user-images.githubusercontent.com/60901094/99726769-f20e3880-2a84-11eb-97bd-98b272963f1d.png">
