### ISSUE TITLE
IBM VPC Cloud Provider Future Features

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-ibm_cloud#92]
## Infrastructure
- [x] Use OpenAPI-based ruby gem for IBM Cloud SDK
- [ ] Add proxy config to provider

## Lifecycle
- [x] Provision VM from image/template
- [ ] Provision VM from service (catalog item)
- [ ] Delete VM
- [ ] Modify/resize VM
- [ ] Create/Delete of other resources (storage, network, etc.)

## Discovery of additional Resources
- [ ] Public gateways
- [ ] VPN gateways
- [ ] ACLs
- [ ] Load balancers

## Manageiq services
- [ ] Metrics collection
- [ ] Events

## PaaS services
- [ ] Managed DBs: https://github.com/ManageIQ/manageiq/issues/20221

## Other tasks
- [ ] MAC addresses (?)

**Comment by chessbyte** [comment]
@agrare is this current?  should this be merged into branch-specific feature epics that we maintain?

**Comment by agrare** [comment]
This has been replaced with release-specific issues, closing
