### ISSUE TITLE
Some VM operating systems are not mapped to a proper icon

### ISSUE THREAD

**Issue by chadh1313** [ManageIQ/manageiq-providers-ibm_cloud#94]
Add any associated mapping for non-standard OS names coming from IBM Cloud.  For example `red-7-amd64`:

![image](https://user-images.githubusercontent.com/3876941/97311665-facf6e00-183a-11eb-8072-dbb5b2ce62c8.png)

**Comment by jaywcarman** [comment]
PowerVS uses a lookup table in our parser to translate to the `OperatingSystem` model `os_map`:

https://github.com/ManageIQ/manageiq-providers-ibm_cloud/blob/master/app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb#L8-L14

https://github.com/ManageIQ/manageiq/blob/master/app/models/operating_system.rb#L13-L34

**Comment by chadh1313** [comment]
Fixed via https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/113
