### ISSUE TITLE
Public/floating IP addresses are not associated with their respective instances

### ISSUE THREAD

**Issue by chadh1313** [ManageIQ/manageiq-providers-ibm_cloud#95]
Would expect this to appear in the instances list and instance details page

![image](https://user-images.githubusercontent.com/3876941/97311988-5ef23200-183b-11eb-92b1-8847e21eed71.png)

![image](https://user-images.githubusercontent.com/3876941/97312045-6dd8e480-183b-11eb-8571-98373dcdd994.png)

**Comment by chessbyte** [comment]
@jaredm-ibm if you can confirm that this works with #200, then please close this issue.

**Comment by jaredm-ibm** [comment]
Yes, I need to capture screen shots then I will close.

**Comment by jaredm-ibm** [comment]
# Instances list shows both IPs

<img width="522" alt="Screen Shot 2021-05-07 at 10 22 04 AM" src="https://user-images.githubusercontent.com/60901094/117464231-74e55b80-af1e-11eb-9d3d-b245a34464a6.png">

# details page shows both IPs

<img width="378" alt="Screen Shot 2021-05-07 at 10 25 21 AM" src="https://user-images.githubusercontent.com/60901094/117464395-9ba39200-af1e-11eb-983c-fd3ebeff9e49.png">
