### ISSUE TITLE
IBM Cloud VPC - missing details, relationships with Floating IP addresses

### ISSUE THREAD

**Issue by chadh1313** [ManageIQ/manageiq-providers-ibm_cloud#99]
1) In IBM Cloud VPC Network Manager, select the Floating IP list is missing details: `Fixed Address`, `Instance name`, `Network Port name`

![image](https://user-images.githubusercontent.com/3876941/97314271-e771d200-183d-11eb-8d77-84f44dc6ae1f.png)

As all these public IP addresses are associated with a private IP on a port/instance, these relationships should be possible.

2) The Network Manager provider overview page shows a count of Floating IPs in the relationships

![image](https://user-images.githubusercontent.com/3876941/97314593-40da0100-183e-11eb-8de0-869b04d80ee4.png)

However, when select a particular cloud network, that hosts the instances using these addresses, the Floating IP count is zero (or some lesser number).  Would think that since the network manager knows the ports, private IP addresses, etc. the associated Public/Floating IPs would be part of the individual network overview page.

![image](https://user-images.githubusercontent.com/3876941/97314861-80085200-183e-11eb-9dbc-d2686ad3fe95.png)

Note: this behavior is also observed with the AWS provider, so either this is working as designed, or is a defect with that provider as well.

**Comment by jaredm-ibm** [comment]
1. Details are filled out: 
<img width="741" alt="Screen Shot 2021-05-07 at 10 27 37 AM" src="https://user-images.githubusercontent.com/60901094/117464675-e6bda500-af1e-11eb-9a54-e2ae17e6f48f.png">

2. Floating IP in network manager

<img width="312" alt="Screen Shot 2021-05-07 at 10 35 12 AM" src="https://user-images.githubusercontent.com/60901094/117465742-ff7a8a80-af1f-11eb-9af7-ed49654c7c7c.png">

3. Floating IP details in network manager with 1 bound floating IP and 1 unbound.

<img width="1011" alt="Screen Shot 2021-05-07 at 10 34 53 AM" src="https://user-images.githubusercontent.com/60901094/117465840-16b97800-af20-11eb-8071-4739d3c64091.png">
